puts 'seeding'

user = User.create(name: 'justin')
user2 = User.create(name: 'throsby')
user3 = User.create(name: 'max')

war = Game.create(name: 'War')

Card.create!(value: 2, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/2D.png', name: '2', game_id: war.id)
Card.create(value: 2, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/2C.png', name: '2', game_id: war.id)
Card.create(value: 2, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/2H.png', name: '2', game_id: war.id)
Card.create(value: 2, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/2S.png', name: '2', game_id: war.id)
Card.create(value: 3, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/3D.png', name: '3', game_id: war.id)
Card.create(value: 3, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/3C.png', name: '3', game_id: war.id)
Card.create(value: 3, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/3H.png', name: '3', game_id: war.id)
Card.create(value: 3, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/3S.png', name: '3', game_id: war.id)
Card.create(value: 4, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/4D.png', name: '4', game_id: war.id)
Card.create(value: 4, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/4C.png', name: '4', game_id: war.id)
Card.create(value: 4, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/4H.png', name: '4', game_id: war.id)
Card.create(value: 4, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/4S.png', name: '4', game_id: war.id)
Card.create(value: 5, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/5D.png', name: '5', game_id: war.id)
Card.create(value: 5, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/5C.png', name: '5', game_id: war.id)
Card.create(value: 5, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/5H.png', name: '5', game_id: war.id)
Card.create(value: 5, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/5S.png', name: '5', game_id: war.id)
Card.create(value: 6, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/6D.png', name: '6', game_id: war.id)
Card.create(value: 6, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/6C.png', name: '6', game_id: war.id)
Card.create(value: 6, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/6H.png', name: '6', game_id: war.id)
Card.create(value: 6, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/6S.png', name: '6', game_id: war.id)
Card.create(value: 7, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/7D.png', name: '7', game_id: war.id)
Card.create(value: 7, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/7C.png', name: '7', game_id: war.id)
Card.create(value: 7, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/7H.png', name: '7', game_id: war.id)
Card.create(value: 7, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/7S.png', name: '7', game_id: war.id)
Card.create(value: 8, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/8D.png', name: '8', game_id: war.id)
Card.create(value: 8, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/8C.png', name: '8', game_id: war.id)
Card.create(value: 8, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/8H.png', name: '8', game_id: war.id)
Card.create(value: 8, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/8S.png', name: '8', game_id: war.id)
Card.create(value: 9, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/9D.png', name: '9', game_id: war.id)
Card.create(value: 9, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/9C.png', name: '9', game_id: war.id)
Card.create(value: 9, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/9H.png', name: '9', game_id: war.id)
Card.create(value: 9, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/9S.png', name: '9', game_id: war.id)
Card.create(value: 10, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/10D.png', name: '10', game_id: war.id)
Card.create(value: 10, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/10C.png', name: '10', game_id: war.id)
Card.create(value: 10, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/10H.png', name: '10', game_id: war.id)
Card.create(value: 10, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/10S.png', name: '10', game_id: war.id)
Card.create(value: 11, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/JD.png', name: 'Jack', game_id: war.id)
Card.create(value: 11, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/JC.png', name: 'Jack', game_id: war.id)
Card.create(value: 11, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/JH.png', name: 'Jack', game_id: war.id)
Card.create(value: 11, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/JS.png', name: 'Jack', game_id: war.id)
Card.create(value: 12, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/QD.png', name: 'Queen', game_id: war.id)
Card.create(value: 12, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/QC.png', name: 'Queen', game_id: war.id)
Card.create(value: 12, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/QH.png', name: 'Queen', game_id: war.id)
Card.create(value: 12, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/QS.png', name: 'Queen', game_id: war.id)
Card.create(value: 13, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/KD.png', name: 'King', game_id: war.id)
Card.create(value: 13, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/KC.png', name: 'King', game_id: war.id)
Card.create(value: 13, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/KH.png', name: 'King', game_id: war.id)
Card.create(value: 13, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/KS.png', name: 'King', game_id: war.id)
Card.create(value: 14, suit: 'Diamond', image: 'https://deckofcardsapi.com/static/img/AD.png', name: 'Ace', game_id: war.id)
Card.create(value: 14, suit: 'Clubs', image: 'https://deckofcardsapi.com/static/img/AC.png', name: 'Ace', game_id: war.id)
Card.create(value: 14, suit: 'Hearts', image: 'https://deckofcardsapi.com/static/img/AH.png', name: 'Ace', game_id: war.id)
Card.create(value: 14, suit: 'Spades', image: 'https://deckofcardsapi.com/static/img/AS.png', name: 'Ace', game_id: war.id)

puts 'seeding done'
